/**
 * Step 7 — Write .env and exit.
 *
 * If a .env exists already we back it up to .env.bak.<timestamp> rather
 * than overwriting silently. The delegate gets a clear note about it.
 *
 * .env values are written with printf-style writes (no trailing newlines on
 * values themselves) so strict-equality flag checks elsewhere don't trip on
 * "true\n".
 */

import * as p from '@clack/prompts';
import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import { stageHeader, finaleSummary, dim, teal } from '../theme.js';
import { REGIONS, findMarketplace } from '../marketplaces.js';
import type { SetupState } from '../state.js';

export async function finaliseStage(state: SetupState, repoRoot: string): Promise<SetupState> {
  stageHeader(7, 7, 'Save credentials and finish');

  if (!state.spApi || !state.region || !state.primaryMarketplaceId) {
    throw new Error('Missing state. Re-run setup from the start.');
  }

  const envPath = join(repoRoot, '.env');
  const region = REGIONS[state.region];
  const primary = findMarketplace(state.primaryMarketplaceId);
  if (!primary) throw new Error(`Unknown marketplace ID: ${state.primaryMarketplaceId}`);

  // Back up existing .env if present
  if (existsSync(envPath)) {
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const backup = `${envPath}.bak.${ts}`;
    copyFileSync(envPath, backup);
    p.log.info(`${dim('Existing .env backed up to')}  ${teal(backup)}`);
  }

  const enabledIds = (state.enabledMarketplaceIds ?? [primary.id]).join(',');

  const envContent = [
    `# Generated by amazon-operator-stack setup wizard at ${new Date().toISOString()}`,
    `# Do not commit this file. It contains credentials specific to your seller account.`,
    ``,
    `# SP-API — LWA app credentials`,
    `SP_API_CLIENT_ID=${state.spApi.clientId}`,
    `SP_API_CLIENT_SECRET=${state.spApi.clientSecret}`,
    `SP_API_REFRESH_TOKEN=${state.spApi.refreshToken}`,
    ``,
    `# SP-API — primary marketplace + region`,
    `SP_API_MARKETPLACE_ID=${primary.id}`,
    `SP_API_MARKETPLACE_CODE=${primary.code}`,
    `SP_API_ENABLED_MARKETPLACE_IDS=${enabledIds}`,
    `SP_API_REGION=${region.spApiAwsRegion}`,
    `SP_API_ENDPOINT=${region.spApiEndpoint}`,
    ``,
    `# Ads API — set these when you finish the homework in HOMEWORK.md`,
    `ADS_API_CLIENT_ID=`,
    `ADS_API_CLIENT_SECRET=`,
    `ADS_API_REFRESH_TOKEN=`,
    `ADS_API_REGION=${state.region}`,
    `ADS_API_ENDPOINT=${region.adsApiEndpoint}`,
    `ADS_PROFILE_ID=`,
    ``,
    `# Operator stack`,
    `LOG_LEVEL=info`,
    ``,
  ].join('\n');

  writeFileSync(envPath, envContent, { encoding: 'utf8', mode: 0o600 });

  // The Ads API entries are intentionally blank but the config loader requires
  // them. Stub the loader requirement by writing placeholders the server will
  // accept as "Ads API not configured" rather than throwing on missing var.
  const stubbedEnv = readFileSync(envPath, 'utf8')
    .replace('ADS_API_CLIENT_ID=\n', 'ADS_API_CLIENT_ID=not-configured\n')
    .replace('ADS_API_CLIENT_SECRET=\n', 'ADS_API_CLIENT_SECRET=not-configured\n')
    .replace('ADS_API_REFRESH_TOKEN=\n', 'ADS_API_REFRESH_TOKEN=not-configured\n');
  writeFileSync(envPath, stubbedEnv, { encoding: 'utf8', mode: 0o600 });

  finaleSummary({
    marketplace: primary.label,
    envFilePath: envPath,
    toolsAvailable: countToolsAvailable(state),
  });

  return { ...state, lastCompletedStage: 'finalise' };
}

function countToolsAvailable(state: SetupState): number {
  // Count probe results that came back ok or role_granted_param
  if (!state.probe) return 0;
  return state.probe.results.filter(
    r => r.status === 'ok' || r.status === 'role_granted_param',
  ).length;
}
